feat: add relay (KS2E-M-DC5)
wokwi/wokwi-elements pull request #120
Opened 2022-01-30 12:18 UTC by Ajtak

Add relay (KS2E-M-DC5)

2022-01-30 18:34 UTC, urish requested changes
Thanks for contributing this element! Please see my comments on the code. Cheers!

2022-01-30 18:34 UTC, urish commented on src/ks2e-m-dc5-element.ts
> +          </marker>
What are all those markers? I don't think they are relevant to the drawing, so let's remove them

2022-01-30 18:34 UTC, urish commented on src/ks2e-m-dc5-element.ts
> +        height="21mm"
Looking at the [data sheet](https://www.datasheetq.com/datasheet-download/752684/1/KEPONT/KS2E-M-DC5), it seems like the size of the element is 21 x 10 x 12mm, so the width should be 21mm and the height should be 10mm. 

This probably means the smaller text ("DC 5V               1A/125V AC               2A/⠀30V DC") will be too small to read - so it's fine to remove it

2022-01-30 18:34 UTC, urish commented on src/ks2e-m-dc5-element.ts
> +        height="21mm"
Also, changing the size means that the positions of the pins in pinInfo will have to be updated

2022-01-30 18:34 UTC, urish commented on src/ks2e-m-dc5-element.ts
> +  x4pos = 155.8;
Let's move those outside the class and declare them using const, e.g. 

```js
const y1Pos = 8.85;
const y2Pos = 70.5;
const x1Pos = 14.7;
const x2Pos = 55;
const x3Pos = 95.3;
const x4Pos = 155.8;
```

Then below, just use them without `this.` in front (also note I made the "P" in "Pos" upper case, to keep it consistent with the naming convention of the project)

2022-01-30 18:34 UTC, urish commented on src/ks2e-m-dc5-element.ts
> +      { name: '16', x: this.x4pos, y: this.y2pos, signals: [], description: '16' },
I think it's better to use descriptive pin names: COIL1, COIL2 for the coil pins, then P1 / NO1 / NC1 (normally open / normally closed), P2, NO2, NC2  for the pole pins.

The pin number can go into the "number" field (e.g. number: 16), and the description can be left out (or just "Common Terminal of POLE1", "Normally Closed Terminal of POLE1"), etc.

2022-01-31 14:51 UTC, Ajtak commented
I'm created commit with fixed changes.

2022-01-31 16:31 UTC, merged

2022-01-31 16:31 UTC, urish commented
Thank you!